import Head from 'next/head';

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service – SignMeNot</title>
        <meta name="robots" content="noindex" />
      </Head>
      <div className="min-h-screen px-6 py-10 bg-slate-900 text-white">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-4">Terms of Service</h1>
          <p className="mb-4">Last updated: July 2025</p>
          <p className="mb-4">
            These Terms of Service ("Terms") govern your use of the SignMeNot website and services. By using our site, you agree to be bound by these Terms.
          </p>
          <h2 className="text-xl font-semibold mt-6 mb-2">1. Use of Service</h2>
          <p className="mb-4">You may use SignMeNot for lawful purposes only. You agree not to misuse the service.</p>
          <h2 className="text-xl font-semibold mt-6 mb-2">2. AI Summary Limitations</h2>
          <p className="mb-4">Summaries provided by SignMeNot are generated by AI and should not be considered legal advice.</p>
          <h2 className="text-xl font-semibold mt-6 mb-2">3. Limitation of Liability</h2>
          <p className="mb-4">We are not liable for decisions made based on AI-generated summaries.</p>
          <p className="mt-8 text-gray-400">Questions? Contact us at contact@signmenot.com</p>
        </div>
      </div>
    </>
  );
}
