// pages/terms.js

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service – SignMeNot</title>
        <meta name="robots" content="noindex" />
      </Head>

      <main className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-700 text-white flex items-start justify-center px-4 py-10">
        <div className="bg-slate-800 rounded-3xl shadow-2xl w-full max-w-3xl p-8 md:p-10">

          {/* Header */}
          <header className="text-center mb-8">
            <div className="mx-auto mb-4 w-48 h-16 relative">
              <Image
                src="/logo.png"
                alt="SignMeNot Logo"
                fill
                style={{ objectFit: 'contain' }}
              />
            </div>
            <p className="text-gray-300 text-sm md:text-base">
              AI that helps you understand terms and policies — instantly and clearly.
            </p>
          </header>

          {/* Terms Content */}
          <article className="prose prose-invert max-w-none">
            <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
            <p className="text-gray-400 mb-6">Last updated: July 2025</p>

            <p className="mb-4">
              These Terms of Service ("Terms") govern your use of the SignMeNot website and services. By using our site, you agree to be bound by these Terms.
            </p>

            <h2 className="text-xl font-semibold mt-6 mb-2">1. Use of Service</h2>
            <p className="mb-4">
              You may use SignMeNot for lawful purposes only. You agree not to misuse the service.
            </p>

            <h2 className="text-xl font-semibold mt-6 mb-2">2. AI Summary Limitations</h2>
            <p className="mb-4">
              Summaries provided by SignMeNot are generated by AI and should not be considered legal advice.
            </p>

            <h2 className="text-xl font-semibold mt-6 mb-2">3. Limitation of Liability</h2>
            <p className="mb-4">
              We are not liable for decisions made based on AI-generated summaries.
            </p>

            <p className="mt-8 text-gray-400">
              Questions? Contact us at <a href="mailto:contact@signmenot.com" className="underline hover:text-white">contact@signmenot.com</a>
            </p>
          </article>

          {/* Back Link */}
          <div className="mt-8">
            <Link href="/" className="inline-block text-blue-400 hover:text-blue-300 underline">
              ← Back to Home
            </Link>
          </div>

          {/* Footer */}
          <footer className="mt-12 text-center text-xs text-gray-500 border-t border-slate-600 pt-6">
            © {new Date().getFullYear()} SignMeNot.
            <Link href="/terms" className="ml-4 underline hover:text-white">Terms</Link>
            <Link href="/privacy" className="ml-4 underline hover:text-white">Privacy</Link>
            <a href="mailto:support@signmenot.com" className="ml-4 underline hover:text-white">Contact</a>
          </footer>
        </div>
      </main>
    </>
  )
}
